FROM lumeo/gateway-balena-jetson-orin-agx-devkit:1.16.26

# FIXME: The below doesnt seem to work within the container - but is something you'd
# want to do to auto set Jetsons to max performance.
#RUN echo 'ACTION=="add", SUBSYSTEMS=="usb", RUN+="/usr/sbin/nvpmodel -m 2" ' > /etc/udev/rules.d/101-nvpmodel.rules

ENTRYPOINT ["/etc/init/run.sh"]
